### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jonas-frey** [Pezmc/BibLatex-Check#54]
**Describe the bug**
Just tried the script with a small bibtex file and it gives the error message 
```
INFO: Reading references from 'test.bib'
INFO: Filtering by references found in 'references.aux'
WARNING: Aux file 'references.aux' doesn't exist -> not restricting entries
Traceback (most recent call last):
  File "/home/jonas/shared/bin/biblatex_check.py", line 473, in <module>
    handleEntryEnding(bibLineNumber, bibLine)
  File "/home/jonas/shared/bin/biblatex_check.py", line 355, in handleEntryEnding
    entryProblemsHTML = generateEntryProblemsHTML(
  File "/home/jonas/shared/bin/biblatex_check.py", line 243, in generateEntryProblemsHTML
    html += "<div class='reference'>" + title + " (" + author + ")"
TypeError: can only concatenate str (not "filter") to str
```
I'm using ubuntu 21.04 and replaced the `python` in the first line of the script by a `python3`.

**To Reproduce**
Execute the script with the command line 
```
biblatex_check.py -b test.bib
``
where the file test.bib contains the following:
```
@book {hartshorne1977algebraic,
    AUTHOR = {Hartshorne, R.},
     TITLE = {Algebraic geometry},
      NOTE = {Graduate Texts in Mathematics, No. 52},
 PUBLISHER = {Springer-Verlag, New York-Heidelberg},
      YEAR = {1977},
     PAGES = {xvi+496},
      ISBN = {0-387-90244-9},
   MRCLASS = {14-01},
  MRNUMBER = {0463157 (57 \#3116)},
MRREVIEWER = {Robert Speiser},
}
```

**Expected behavior**

Should tell me that the bibtex file is correct.

**Comment by Pezmc** [comment]
Thank you for the detailed writeup, I can confirm I was able to reproduce locally when using Python 3.9 (but not using 2.0).

```
/biblatex_check.py -b test.bib
INFO: Reading references from 'test.bib'
INFO: Filtering by references found in 'references.aux'
WARNING: Aux file 'references.aux' doesn't exist -> not restricting entries
Traceback (most recent call last):
  File "/Users/pezcuckow/Git/BibLatex-Check/./biblatex_check.py", line 473, in <module>
    handleEntryEnding(bibLineNumber, bibLine)
  File "/Users/pezcuckow/Git/BibLatex-Check/./biblatex_check.py", line 355, in handleEntryEnding
    entryProblemsHTML = generateEntryProblemsHTML(
  File "/Users/pezcuckow/Git/BibLatex-Check/./biblatex_check.py", line 243, in generateEntryProblemsHTML
    html += "<div class='reference'>" + title + " (" + author + ")"
TypeError: can only concatenate str (not "filter") to str
```
